read house price dataset , scale the featyures of the dataset using sa standard scaler and implement lasso regression with high alpha value to demostarate feature selection idetify which coefficients were reduced to exactly zero

read the std marks data csv dataset and hadndle missing values . define multiple predictor variables and a signle target variable to train a multiple linear regression model with an 80:20 split and evaluate the final predictions using the mean suquared error metric

In [139]:
import pandas as pd
import numpy as np

In [140]:
house_data = pd.read_csv("../datasets/House Price India.csv")
house_data.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0.0,122003.0,52.8645,-114.557,2880,5400,2,58.0,2380000.0
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0.0,122004.0,52.8878,-114.470,2470,4000,2,51.0,1400000.0
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0.0,122004.0,52.8852,-114.468,2940,6600,1,53.0,1200000.0
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0.0,122005.0,52.9532,-114.321,3350,42847,3,76.0,838000.0
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0.0,122006.0,52.9047,-114.485,2060,4500,1,51.0,805000.0

In [141]:
house_data.isnull().sum()

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                1
Price                                    1
dtype: int64

In [142]:
house_data.fillna(house_data["Distance from the airport"].mean(),inplace=True)
house_data.fillna(house_data["Price"].mean(),inplace=True)

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0.0,122003.0,52.8645,-114.557,2880,5400,2,58.0,2380000.0
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0.0,122004.0,52.8878,-114.470,2470,4000,2,51.0,1400000.0
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0.0,122004.0,52.8852,-114.468,2940,6600,1,53.0,1200000.0
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0.0,122005.0,52.9532,-114.321,3350,42847,3,76.0,838000.0
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0.0,122006.0,52.9047,-114.485,2060,4500,1,51.0,805000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14615,6762830250,42734,2,1.50,1556,20000,1.0,0,0,4,...,1957,0.0,122066.0,52.6191,-114.472,2250,17286,3,76.0,221700.0
14616,6762830339,42734,3,2.00,1680,7000,1.5,0,0,4,...,1968,0.0,122072.0,52.5075,-114.393,1540,7480,3,59.0,219200.0
14617,6762830618,42734,2,1.00,1070,6120,1.0,0,0,3,...,1962,0.0,122056.0,52.7289,-114.507,1130,6120,2,64.0,209000.0
14618,6762830709,42734,4,1.00,1030,6621,1.0,0,0,4,...,1955,0.0,122042.0,52.7157,-114.411,1420,6631,3,54.0,205000.0
14619,6762831463,42734,3,1.00,900,4770,1.0,0,0,3,...,1969,2009.0,122018.0,52.5338,-114.552,900,3480,2,55.0,146000.0

In [143]:
x = house_data.iloc[:,2:-1]
y = house_data.iloc[:,-1]

In [144]:
from sklearn.preprocessing import StandardScaler

In [145]:
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [146]:
from sklearn.model_selection import train_test_split

In [147]:
x_train , x_test , y_train , y_test = train_test_split(x,y,random_state=42 , test_size=0.2)

In [148]:
from sklearn.linear_model import Lasso

In [149]:
model = Lasso(alpha=0.1)
model.fit(x_train,y_train)
y_predict = model.predict(x_test)

/home/dharmraj/Desktop/ML/.venv/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.995e+14, tolerance: 1.601e+11
  model = cd_fast.enet_coordinate_descent(

In [150]:
model.coef_

array([-4.15102438e+04,  1.04160648e+04,  2.82354706e+05, -6.69305323e+03,
        1.01451746e+03,  1.54578487e+04,  5.75353616e+04,  5.46540942e+05,
        1.14763862e+05, -8.60928811e+04, -4.95753913e+04, -1.48486154e+06,
        2.33832580e+04, -9.84610151e+05,  6.13861236e+05, -7.12983451e+05,
        5.80565869e+03, -1.33983291e+04,  4.00779560e+04, -4.09037169e+03])

In [151]:
from sklearn.metrics import mean_absolute_error

In [152]:
mean_absolute_error(y_test, y_predict)

137415.40995869986

# 2.

In [153]:
std_mark = pd.read_csv("../datasets/std_marks_data.csv")

In [154]:
std_mark.isnull().sum()

hours       12
age          0
internet     0
marks        0
dtype: int64

In [155]:
std_mark.fillna(std_mark["hours"].mean(),inplace=True)

        hours  age  internet  marks
0    6.840000   15         0  78.64
1    6.560000   20         1  88.80
2    5.494514   21         1  88.90
3    8.670000   22         1  98.99
4    7.550000   17         1  92.34
..        ...  ...       ...    ...
295  2.990000   25         0  43.45
296  6.550000   15         1  77.74
297  0.000000   20         1  75.76
298  9.900000   22         0  99.99
299  3.400000   21         0  99.99

[300 rows x 4 columns]

In [156]:
x = std_mark.iloc[:,:-1]
y = std_mark.iloc[:,-1]

In [157]:
scaler = StandardScaler()
x_scaler = scaler.fit_transform(x)

In [158]:
x_train , x_test , y_train , y_test = train_test_split(x_scaler , y , random_state=42, test_size=0.2)

In [159]:
from sklearn.linear_model import LinearRegression

In [160]:
model = LinearRegression()
model.fit(x_train , y_train)
y_predict = model.predict(x_test)

In [161]:
from sklearn.metrics import mean_squared_error

In [162]:
mean_squared_error(y_test , y_predict)

296.9278739472545